(function(){var a;function diff_match_patch(){function b(){for(var c=0,e=1,d=2;e!=d;){c++;e=d;d<<=1}return c}this.Diff_Timeout=1;this.Diff_EditCost=4;this.Diff_DualThreshold=32;this.Match_Threshold=0.5;this.Match_Distance=1E3;this.Patch_DeleteThreshold=0.5;this.Patch_Margin=4;this.Match_MaxBits=b()}a=diff_match_patch.prototype;
a.diff_main=function(b,c,e){if(b==null||c==null)throw Error("Null input. (diff_main)");if(b==c)return[[0,b]];if(typeof e=="undefined")e=true;var d=e,f=this.diff_commonPrefix(b,c);e=b.substring(0,f);b=b.substring(f);c=c.substring(f);f=this.diff_commonSuffix(b,c);var g=b.substring(b.length-f);b=b.substring(0,b.length-f);c=c.substring(0,c.length-f);b=this.diff_compute(b,c,d);e&&b.unshift([0,e]);g&&b.push([0,g]);this.diff_cleanupMerge(b);return b};
a.diff_compute=function(b,c,e){var d;if(!b)return[[1,c]];if(!c)return[[-1,b]];d=b.length>c.length?b:c;var f=b.length>c.length?c:b,g=d.indexOf(f);if(g!=-1){d=[[1,d.substring(0,g)],[0,f],[1,d.substring(g+f.length)]];if(b.length>c.length)d[0][0]=d[2][0]=-1;return d}if(d=this.diff_halfMatch(b,c)){var h=d[0];b=d[1];f=d[2];c=d[3];d=d[4];h=this.diff_main(h,f,e);e=this.diff_main(b,c,e);return h.concat([[0,d]],e)}if(e&&(b.length<100||c.length<100))e=false;if(e){h=this.diff_linesToChars(b,c);b=h[0];c=h[1];
h=h[2]}(d=this.diff_map(b,c))||(d=[[-1,b],[1,c]]);if(e){this.diff_charsToLines(d,h);this.diff_cleanupSemantic(d);d.push([0,""]);c=b=e=0;for(f=h="";e<d.length;){switch(d[e][0]){case 1:c++;f+=d[e][1];break;case -1:b++;h+=d[e][1];break;case 0:if(b>=1&&c>=1){h=this.diff_main(h,f,false);d.splice(e-b-c,b+c);e=e-b-c;for(b=h.length-1;b>=0;b--)d.splice(e,0,h[b]);e+=h.length}b=c=0;f=h="";break}e++}d.pop()}return d};
a.diff_linesToChars=function(b,c){function e(i){for(var k="",j=0,l=-1,m=d.length;l<i.length-1;){l=i.indexOf("\n",j);if(l==-1)l=i.length-1;var p=i.substring(j,l+1);j=l+1;if(f.hasOwnProperty?f.hasOwnProperty(p):f[p]!==undefined)k+=String.fromCharCode(f[p]);else{k+=String.fromCharCode(m);f[p]=m;d[m++]=p}}return k}var d=[],f={};d[0]="";var g=e(b),h=e(c);return[g,h,d]};
a.diff_charsToLines=function(b,c){for(var e=0;e<b.length;e++){for(var d=b[e][1],f=[],g=0;g<d.length;g++)f[g]=c[d.charCodeAt(g)];b[e][1]=f.join("")}};
a.diff_map=function(b,c){var e=(new Date).getTime()+this.Diff_Timeout*1E3,d=b.length,f=c.length,g=d+f-1,h=this.Diff_DualThreshold*2<g,i=[],k=[],j={},l={};j[1]=0;l[1]=0;for(var m,p,n,o={},s=false,u=!!o.hasOwnProperty,t=(d+f)%2,q=0;q<g;q++){if(this.Diff_Timeout>0&&(new Date).getTime()>e)return null;i[q]={};for(var r=-q;r<=q;r+=2){m=r==-q||r!=q&&j[r-1]<j[r+1]?j[r+1]:j[r-1]+1;p=m-r;if(h){n=m+","+p;if(t&&(u?o.hasOwnProperty(n):o[n]!==undefined))s=true;t||(o[n]=q)}for(;!s&&m<d&&p<f&&b.charAt(m)==c.charAt(p);){m++;
p++;if(h){n=m+","+p;if(t&&(u?o.hasOwnProperty(n):o[n]!==undefined))s=true;t||(o[n]=q)}}j[r]=m;i[q][m+","+p]=true;if(m==d&&p==f)return this.diff_path1(i,b,c);else if(s){k=k.slice(0,o[n]+1);e=this.diff_path1(i,b.substring(0,m),c.substring(0,p));return e.concat(this.diff_path2(k,b.substring(m),c.substring(p)))}}if(h){k[q]={};for(r=-q;r<=q;r+=2){m=r==-q||r!=q&&l[r-1]<l[r+1]?l[r+1]:l[r-1]+1;p=m-r;n=d-m+","+(f-p);if(!t&&(u?o.hasOwnProperty(n):o[n]!==undefined))s=true;if(t)o[n]=q;for(;!s&&m<d&&p<f&&b.charAt(d-
m-1)==c.charAt(f-p-1);){m++;p++;n=d-m+","+(f-p);if(!t&&(u?o.hasOwnProperty(n):o[n]!==undefined))s=true;if(t)o[n]=q}l[r]=m;k[q][m+","+p]=true;if(s){i=i.slice(0,o[n]+1);e=this.diff_path1(i,b.substring(0,d-m),c.substring(0,f-p));return e.concat(this.diff_path2(k,b.substring(d-m),c.substring(f-p)))}}}}return null};
a.diff_path1=function(b,c,e){for(var d=[],f=c.length,g=e.length,h=null,i=b.length-2;i>=0;i--)for(;;)if(b[i].hasOwnProperty?b[i].hasOwnProperty(f-1+","+g):b[i][f-1+","+g]!==undefined){f--;if(h===-1)d[0][1]=c.charAt(f)+d[0][1];else d.unshift([-1,c.charAt(f)]);h=-1;break}else if(b[i].hasOwnProperty?b[i].hasOwnProperty(f+","+(g-1)):b[i][f+","+(g-1)]!==undefined){g--;if(h===1)d[0][1]=e.charAt(g)+d[0][1];else d.unshift([1,e.charAt(g)]);h=1;break}else{f--;g--;if(c.charCodeAt(f)!=e.charCodeAt(g))throw Error("No diagonal.  Can't happen. (diff_path1)");
if(h===0)d[0][1]=c.charAt(f)+d[0][1];else d.unshift([0,c.charAt(f)]);h=0}return d};
a.diff_path2=function(b,c,e){for(var d=[],f=0,g=c.length,h=e.length,i=null,k=b.length-2;k>=0;k--)for(;;)if(b[k].hasOwnProperty?b[k].hasOwnProperty(g-1+","+h):b[k][g-1+","+h]!==undefined){g--;if(i===-1)d[f-1][1]+=c.charAt(c.length-g-1);else d[f++]=[-1,c.charAt(c.length-g-1)];i=-1;break}else if(b[k].hasOwnProperty?b[k].hasOwnProperty(g+","+(h-1)):b[k][g+","+(h-1)]!==undefined){h--;if(i===1)d[f-1][1]+=e.charAt(e.length-h-1);else d[f++]=[1,e.charAt(e.length-h-1)];i=1;break}else{g--;h--;if(c.charCodeAt(c.length-
g-1)!=e.charCodeAt(e.length-h-1))throw Error("No diagonal.  Can't happen. (diff_path2)");if(i===0)d[f-1][1]+=c.charAt(c.length-g-1);else d[f++]=[0,c.charAt(c.length-g-1)];i=0}return d};a.diff_commonPrefix=function(b,c){if(!b||!c||b.charCodeAt(0)!==c.charCodeAt(0))return 0;for(var e=0,d=Math.min(b.length,c.length),f=d,g=0;e<f;){if(b.substring(g,f)==c.substring(g,f))g=e=f;else d=f;f=Math.floor((d-e)/2+e)}return f};
a.diff_commonSuffix=function(b,c){if(!b||!c||b.charCodeAt(b.length-1)!==c.charCodeAt(c.length-1))return 0;for(var e=0,d=Math.min(b.length,c.length),f=d,g=0;e<f;){if(b.substring(b.length-f,b.length-g)==c.substring(c.length-f,c.length-g))g=e=f;else d=f;f=Math.floor((d-e)/2+e)}return f};
a.diff_halfMatch=function(b,c){function e(j,l,m){for(var p=j.substring(m,m+Math.floor(j.length/4)),n=-1,o="",s,u,t,q;(n=l.indexOf(p,n+1))!=-1;){var r=g.diff_commonPrefix(j.substring(m),l.substring(n)),v=g.diff_commonSuffix(j.substring(0,m),l.substring(0,n));if(o.length<v+r){o=l.substring(n-v,n)+l.substring(n,n+r);s=j.substring(0,m-v);u=j.substring(m+r);t=l.substring(0,n-v);q=l.substring(n+r)}}return o.length>=j.length/2?[s,u,t,q,o]:null}var d=b.length>c.length?b:c,f=b.length>c.length?c:b;if(d.length<
10||f.length<1)return null;var g=this,h=e(d,f,Math.ceil(d.length/4));d=e(d,f,Math.ceil(d.length/2));var i;if(!h&&!d)return null;else i=d?h?h[4].length>d[4].length?h:d:d:h;var k;if(b.length>c.length){h=i[0];d=i[1];f=i[2];k=i[3]}else{f=i[0];k=i[1];h=i[2];d=i[3]}i=i[4];return[h,d,f,k,i]};
a.diff_cleanupSemantic=function(b){for(var c=false,e=[],d=0,f=null,g=0,h=0,i=0;g<b.length;){if(b[g][0]==0){e[d++]=g;h=i;i=0;f=b[g][1]}else{i+=b[g][1].length;if(f!==null&&f.length<=h&&f.length<=i){b.splice(e[d-1],0,[-1,f]);b[e[d-1]+1][0]=1;d--;d--;g=d>0?e[d-1]:-1;i=h=0;f=null;c=true}}g++}c&&this.diff_cleanupMerge(b);this.diff_cleanupSemanticLossless(b)};
a.diff_cleanupSemanticLossless=function(b){function c(u,t){if(!u||!t)return 5;var q=0;if(u.charAt(u.length-1).match(e)||t.charAt(0).match(e)){q++;if(u.charAt(u.length-1).match(d)||t.charAt(0).match(d)){q++;if(u.charAt(u.length-1).match(f)||t.charAt(0).match(f)){q++;if(u.match(g)||t.match(h))q++}}}return q}for(var e=/[^a-zA-Z0-9]/,d=/\s/,f=/[\r\n]/,g=/\n\r?\n$/,h=/^\r?\n\r?\n/,i=1;i<b.length-1;){if(b[i-1][0]==0&&b[i+1][0]==0){var k=b[i-1][1],j=b[i][1],l=b[i+1][1],m=this.diff_commonSuffix(k,j);if(m){var p=
j.substring(j.length-m);k=k.substring(0,k.length-m);j=p+j.substring(0,j.length-m);l=p+l}m=k;p=j;for(var n=l,o=c(k,j)+c(j,l);j.charAt(0)===l.charAt(0);){k+=j.charAt(0);j=j.substring(1)+l.charAt(0);l=l.substring(1);var s=c(k,j)+c(j,l);if(s>=o){o=s;m=k;p=j;n=l}}if(b[i-1][1]!=m){if(m)b[i-1][1]=m;else{b.splice(i-1,1);i--}b[i][1]=p;if(n)b[i+1][1]=n;else{b.splice(i+1,1);i--}}}i++}};
a.diff_cleanupEfficiency=function(b){for(var c=false,e=[],d=0,f="",g=0,h=false,i=false,k=false,j=false;g<b.length;){if(b[g][0]==0){if(b[g][1].length<this.Diff_EditCost&&(k||j)){e[d++]=g;h=k;i=j;f=b[g][1]}else{d=0;f=""}k=j=false}else{if(b[g][0]==-1)j=true;else k=true;if(f&&(h&&i&&k&&j||f.length<this.Diff_EditCost/2&&h+i+k+j==3)){b.splice(e[d-1],0,[-1,f]);b[e[d-1]+1][0]=1;d--;f="";if(h&&i){k=j=true;d=0}else{d--;g=d>0?e[d-1]:-1;k=j=false}c=true}}g++}c&&this.diff_cleanupMerge(b)};
a.diff_cleanupMerge=function(b){b.push([0,""]);for(var c=0,e=0,d=0,f="",g="",h;c<b.length;)switch(b[c][0]){case 1:d++;g+=b[c][1];c++;break;case -1:e++;f+=b[c][1];c++;break;case 0:if(e!==0||d!==0){if(e!==0&&d!==0){h=this.diff_commonPrefix(g,f);if(h!==0){if(c-e-d>0&&b[c-e-d-1][0]==0)b[c-e-d-1][1]+=g.substring(0,h);else{b.splice(0,0,[0,g.substring(0,h)]);c++}g=g.substring(h);f=f.substring(h)}h=this.diff_commonSuffix(g,f);if(h!==0){b[c][1]=g.substring(g.length-h)+b[c][1];g=g.substring(0,g.length-h);f=
f.substring(0,f.length-h)}}if(e===0)b.splice(c-e-d,e+d,[1,g]);else d===0?b.splice(c-e-d,e+d,[-1,f]):b.splice(c-e-d,e+d,[-1,f],[1,g]);c=c-e-d+(e?1:0)+(d?1:0)+1}else if(c!==0&&b[c-1][0]==0){b[c-1][1]+=b[c][1];b.splice(c,1)}else c++;e=d=0;g=f="";break}b[b.length-1][1]===""&&b.pop();e=false;for(c=1;c<b.length-1;){if(b[c-1][0]==0&&b[c+1][0]==0)if(b[c][1].substring(b[c][1].length-b[c-1][1].length)==b[c-1][1]){b[c][1]=b[c-1][1]+b[c][1].substring(0,b[c][1].length-b[c-1][1].length);b[c+1][1]=b[c-1][1]+b[c+
1][1];b.splice(c-1,1);e=true}else if(b[c][1].substring(0,b[c+1][1].length)==b[c+1][1]){b[c-1][1]+=b[c+1][1];b[c][1]=b[c][1].substring(b[c+1][1].length)+b[c+1][1];b.splice(c+1,1);e=true}c++}e&&this.diff_cleanupMerge(b)};a.diff_xIndex=function(b,c){var e=0,d=0,f=0,g=0,h;for(h=0;h<b.length;h++){if(b[h][0]!==1)e+=b[h][1].length;if(b[h][0]!==-1)d+=b[h][1].length;if(e>c)break;f=e;g=d}if(b.length!=h&&b[h][0]===-1)return g;return g+(c-f)};
a.diff_prettyHtml=function(b){for(var c=[],e=0,d=0;d<b.length;d++){var f=b[d][0],g=b[d][1],h=g.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/\n/g,"&para;<BR>");switch(f){case 1:c[d]='<INS STYLE="background:#E6FFE6;" TITLE="i='+e+'">'+h+"</INS>";break;case -1:c[d]='<DEL STYLE="background:#FFE6E6;" TITLE="i='+e+'">'+h+"</DEL>";break;case 0:c[d]='<SPAN TITLE="i='+e+'">'+h+"</SPAN>";break}if(f!==-1)e+=g.length}return c.join("")};
a.diff_text1=function(b){for(var c=[],e=0;e<b.length;e++)if(b[e][0]!==1)c[e]=b[e][1];return c.join("")};a.diff_text2=function(b){for(var c=[],e=0;e<b.length;e++)if(b[e][0]!==-1)c[e]=b[e][1];return c.join("")};a.diff_levenshtein=function(b){for(var c=0,e=0,d=0,f=0;f<b.length;f++){var g=b[f][0],h=b[f][1];switch(g){case 1:e+=h.length;break;case -1:d+=h.length;break;case 0:c+=Math.max(e,d);d=e=0;break}}c+=Math.max(e,d);return c};
a.diff_toDelta=function(b){for(var c=[],e=0;e<b.length;e++)switch(b[e][0]){case 1:c[e]="+"+encodeURI(b[e][1]);break;case -1:c[e]="-"+b[e][1].length;break;case 0:c[e]="="+b[e][1].length;break}return c.join("\t").replace(/\x00/g,"%00").replace(/%20/g," ")};
a.diff_fromDelta=function(b,c){var e=[],d=0,f=0;c=c.replace(/%00/g,"\u0000");for(var g=c.split(/\t/g),h=0;h<g.length;h++){var i=g[h].substring(1);switch(g[h].charAt(0)){case "+":try{e[d++]=[1,decodeURI(i)]}catch(k){throw Error("Illegal escape in diff_fromDelta: "+i);}break;case "-":case "=":var j=parseInt(i,10);if(isNaN(j)||j<0)throw Error("Invalid number in diff_fromDelta: "+i);i=b.substring(f,f+=j);if(g[h].charAt(0)=="=")e[d++]=[0,i];else e[d++]=[-1,i];break;default:if(g[h])throw Error("Invalid diff operation in diff_fromDelta: "+
g[h]);}}if(f!=b.length)throw Error("Delta length ("+f+") does not equal source text length ("+b.length+").");return e};a.match_main=function(b,c,e){if(b==null||c==null||e==null)throw Error("Null input. (match_main)");e=Math.max(0,Math.min(e,b.length));return b==c?0:b.length?b.substring(e,e+c.length)==c?e:this.match_bitap(b,c,e):-1};
a.match_bitap=function(b,c,e){function d(u,t){var q=u/c.length,r=Math.abs(e-t);if(!g.Match_Distance)return r?1:q;return q+r/g.Match_Distance}if(c.length>this.Match_MaxBits)throw Error("Pattern too long for this browser.");var f=this.match_alphabet(c),g=this,h=this.Match_Threshold,i=b.indexOf(c,e);if(i!=-1){h=Math.min(d(0,i),h);i=b.lastIndexOf(c,e+c.length);if(i!=-1)h=Math.min(d(0,i),h)}var k=1<<c.length-1;i=-1;for(var j,l,m=c.length+b.length,p,n=0;n<c.length;n++){j=0;for(l=m;j<l;){if(d(n,e+l)<=h)j=
l;else m=l;l=Math.floor((m-j)/2+j)}m=l;j=Math.max(1,e-l+1);var o=Math.min(e+l,b.length)+c.length;l=Array(o+2);l[o+1]=(1<<n)-1;for(o=o;o>=j;o--){var s=f[b.charAt(o-1)];l[o]=n===0?(l[o+1]<<1|1)&s:(l[o+1]<<1|1)&s|(p[o+1]|p[o])<<1|1|p[o+1];if(l[o]&k){s=d(n,o-1);if(s<=h){h=s;i=o-1;if(i>e)j=Math.max(1,2*e-i);else break}}}if(d(n+1,e)>h)break;p=l}return i};a.match_alphabet=function(b){for(var c={},e=0;e<b.length;e++)c[b.charAt(e)]=0;for(e=0;e<b.length;e++)c[b.charAt(e)]|=1<<b.length-e-1;return c};
a.patch_addContext=function(b,c){if(c.length!=0){for(var e=c.substring(b.start2,b.start2+b.length1),d=0;c.indexOf(e)!=c.lastIndexOf(e)&&e.length<this.Match_MaxBits-this.Patch_Margin-this.Patch_Margin;){d+=this.Patch_Margin;e=c.substring(b.start2-d,b.start2+b.length1+d)}d+=this.Patch_Margin;(e=c.substring(b.start2-d,b.start2))&&b.diffs.unshift([0,e]);(d=c.substring(b.start2+b.length1,b.start2+b.length1+d))&&b.diffs.push([0,d]);b.start1-=e.length;b.start2-=e.length;b.length1+=e.length+d.length;b.length2+=
e.length+d.length}};
a.patch_make=function(b,c,e){var d;if(typeof b=="string"&&typeof c=="string"&&typeof e=="undefined"){d=b;c=this.diff_main(d,c,true);if(c.length>2){this.diff_cleanupSemantic(c);this.diff_cleanupEfficiency(c)}}else if(b&&typeof b=="object"&&typeof c=="undefined"&&typeof e=="undefined"){c=b;d=this.diff_text1(c)}else if(typeof b=="string"&&c&&typeof c=="object"&&typeof e=="undefined"){d=b;c=c}else if(typeof b=="string"&&typeof c=="string"&&e&&typeof e=="object"){d=b;c=e}else throw Error("Unknown call format to patch_make.");if(c.length===
0)return[];e=[];b=new patch_obj;var f=0,g=0,h=0,i=d;d=d;for(var k=0;k<c.length;k++){var j=c[k][0],l=c[k][1];if(!f&&j!==0){b.start1=g;b.start2=h}switch(j){case 1:b.diffs[f++]=c[k];b.length2+=l.length;d=d.substring(0,h)+l+d.substring(h);break;case -1:b.length1+=l.length;b.diffs[f++]=c[k];d=d.substring(0,h)+d.substring(h+l.length);break;case 0:if(l.length<=2*this.Patch_Margin&&f&&c.length!=k+1){b.diffs[f++]=c[k];b.length1+=l.length;b.length2+=l.length}else if(l.length>=2*this.Patch_Margin)if(f){this.patch_addContext(b,
i);e.push(b);b=new patch_obj;f=0;i=d;g=h}break}if(j!==1)g+=l.length;if(j!==-1)h+=l.length}if(f){this.patch_addContext(b,i);e.push(b)}return e};a.patch_deepCopy=function(b){for(var c=[],e=0;e<b.length;e++){var d=b[e],f=new patch_obj;f.diffs=[];for(var g=0;g<d.diffs.length;g++)f.diffs[g]=d.diffs[g].slice();f.start1=d.start1;f.start2=d.start2;f.length1=d.length1;f.length2=d.length2;c[e]=f}return c};
a.patch_apply=function(b,c){if(b.length==0)return[c,[]];b=this.patch_deepCopy(b);var e=this.patch_addPadding(b);c=e+c+e;this.patch_splitMax(b);for(var d=0,f=[],g=0;g<b.length;g++){var h=b[g].start2+d,i=this.diff_text1(b[g].diffs),k,j=-1;if(i.length>this.Match_MaxBits){k=this.match_main(c,i.substring(0,this.Match_MaxBits),h);if(k!=-1){j=this.match_main(c,i.substring(i.length-this.Match_MaxBits),h+i.length-this.Match_MaxBits);if(j==-1||k>=j)k=-1}}else k=this.match_main(c,i,h);if(k==-1){f[g]=false;d-=
b[g].length2-b[g].length1}else{f[g]=true;d=k-h;h=j==-1?c.substring(k,k+i.length):c.substring(k,j+this.Match_MaxBits);if(i==h)c=c.substring(0,k)+this.diff_text2(b[g].diffs)+c.substring(k+i.length);else{h=this.diff_main(i,h,false);if(i.length>this.Match_MaxBits&&this.diff_levenshtein(h)/i.length>this.Patch_DeleteThreshold)f[g]=false;else{this.diff_cleanupSemanticLossless(h);i=0;var l;for(j=0;j<b[g].diffs.length;j++){var m=b[g].diffs[j];if(m[0]!==0)l=this.diff_xIndex(h,i);if(m[0]===1)c=c.substring(0,
k+l)+m[1]+c.substring(k+l);else if(m[0]===-1)c=c.substring(0,k+l)+c.substring(k+this.diff_xIndex(h,i+m[1].length));if(m[0]!==-1)i+=m[1].length}}}}}c=c.substring(e.length,c.length-e.length);return[c,f]};
a.patch_addPadding=function(b){for(var c=this.Patch_Margin,e="",d=1;d<=c;d++)e+=String.fromCharCode(d);for(d=0;d<b.length;d++){b[d].start1+=c;b[d].start2+=c}d=b[0];var f=d.diffs;if(f.length==0||f[0][0]!=0){f.unshift([0,e]);d.start1-=c;d.start2-=c;d.length1+=c;d.length2+=c}else if(c>f[0][1].length){var g=c-f[0][1].length;f[0][1]=e.substring(f[0][1].length)+f[0][1];d.start1-=g;d.start2-=g;d.length1+=g;d.length2+=g}d=b[b.length-1];f=d.diffs;if(f.length==0||f[f.length-1][0]!=0){f.push([0,e]);d.length1+=
c;d.length2+=c}else if(c>f[f.length-1][1].length){g=c-f[f.length-1][1].length;f[f.length-1][1]+=e.substring(0,g);d.length1+=g;d.length2+=g}return e};
a.patch_splitMax=function(b){for(var c=0;c<b.length;c++)if(b[c].length1>this.Match_MaxBits){var e=b[c];b.splice(c--,1);for(var d=this.Match_MaxBits,f=e.start1,g=e.start2,h="";e.diffs.length!==0;){var i=new patch_obj,k=true;i.start1=f-h.length;i.start2=g-h.length;if(h!==""){i.length1=i.length2=h.length;i.diffs.push([0,h])}for(;e.diffs.length!==0&&i.length1<d-this.Patch_Margin;){h=e.diffs[0][0];var j=e.diffs[0][1];if(h===1){i.length2+=j.length;g+=j.length;i.diffs.push(e.diffs.shift());k=false}else if(h===
-1&&i.diffs.length==1&&i.diffs[0][0]==0&&j.length>2*d){i.length1+=j.length;f+=j.length;k=false;i.diffs.push([h,j]);e.diffs.shift()}else{j=j.substring(0,d-i.length1-this.Patch_Margin);i.length1+=j.length;f+=j.length;if(h===0){i.length2+=j.length;g+=j.length}else k=false;i.diffs.push([h,j]);if(j==e.diffs[0][1])e.diffs.shift();else e.diffs[0][1]=e.diffs[0][1].substring(j.length)}}h=this.diff_text2(i.diffs);h=h.substring(h.length-this.Patch_Margin);j=this.diff_text1(e.diffs).substring(0,this.Patch_Margin);
if(j!==""){i.length1+=j.length;i.length2+=j.length;if(i.diffs.length!==0&&i.diffs[i.diffs.length-1][0]===0)i.diffs[i.diffs.length-1][1]+=j;else i.diffs.push([0,j])}k||b.splice(++c,0,i)}}};a.patch_toText=function(b){for(var c=[],e=0;e<b.length;e++)c[e]=b[e];return c.join("")};
a.patch_fromText=function(b){var c=[];if(!b)return c;b=b.replace(/%00/g,"\u0000");b=b.split("\n");for(var e=0;e<b.length;){var d=b[e].match(/^@@ -(\d+),?(\d*) \+(\d+),?(\d*) @@$/);if(!d)throw Error("Invalid patch string: "+b[e]);var f=new patch_obj;c.push(f);f.start1=parseInt(d[1],10);if(d[2]===""){f.start1--;f.length1=1}else if(d[2]=="0")f.length1=0;else{f.start1--;f.length1=parseInt(d[2],10)}f.start2=parseInt(d[3],10);if(d[4]===""){f.start2--;f.length2=1}else if(d[4]=="0")f.length2=0;else{f.start2--;
f.length2=parseInt(d[4],10)}for(e++;e<b.length;){d=b[e].charAt(0);try{var g=decodeURI(b[e].substring(1))}catch(h){throw Error("Illegal escape in patch_fromText: "+g);}if(d=="-")f.diffs.push([-1,g]);else if(d=="+")f.diffs.push([1,g]);else if(d==" ")f.diffs.push([0,g]);else if(d=="@")break;else if(d!=="")throw Error('Invalid patch mode "'+d+'" in: '+g);e++}}return c};function patch_obj(){this.diffs=[];this.start2=this.start1=null;this.length2=this.length1=0}
patch_obj.prototype.toString=function(){var b,c;b=this.length1===0?this.start1+",0":this.length1==1?this.start1+1:this.start1+1+","+this.length1;c=this.length2===0?this.start2+",0":this.length2==1?this.start2+1:this.start2+1+","+this.length2;b=["@@ -"+b+" +"+c+" @@\n"];var e;for(c=0;c<this.diffs.length;c++){switch(this.diffs[c][0]){case 1:e="+";break;case -1:e="-";break;case 0:e=" ";break}b[c+1]=e+encodeURI(this.diffs[c][1])+"\n"}return b.join("").replace(/\x00/g,"%00").replace(/%20/g," ")};
window.diff_match_patch=diff_match_patch;window.patch_obj=patch_obj;window.DIFF_DELETE=-1;window.DIFF_INSERT=1;window.DIFF_EQUAL=0;})()
